In [1]:
!pip install numpy

In [2]:
import numpy as np

#### Array adalah sebuah tipe data yang berisi kumpulan nilai, salah satu bentuk sederhana dari array adalah vector

Vector : 3i + 2j + 3k --> 1D </br>
Matrix : <br> 1 0 1 --> 2D <br>
         1 1 1 <br>
         0 0 1

In [3]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
np.zeros(8) #mengisi array dengan angka 0

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
np.ones(8) #mengisi array dengan angka 1

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
np.arange(8) #mengisi array dengan angka berurut

array([0, 1, 2, 3, 4, 5, 6, 7])

In [11]:
np.arange(0,1,0.08) #mengisi array dengan angka selisih 2

array([0.  , 0.08, 0.16, 0.24, 0.32, 0.4 , 0.48, 0.56, 0.64, 0.72, 0.8 ,
       0.88, 0.96])

In [12]:
np.append(a, [4,3]) #menyambung sesuatu kedalam array

array([1, 2, 3, 4, 3])

In [13]:
np.delete(a, 0) #mendelete array sesuai posisi index

array([2, 3])

In [14]:
arr = np.array([10,4,3,19,2,1,6,18])

In [15]:
np.sort(arr) #mensorting nilai dalam array

array([ 1,  2,  3,  4,  6, 10, 18, 19])

#### Shape and Size

In [16]:
arr

array([10,  4,  3, 19,  2,  1,  6, 18])

In [18]:
arr1 = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])

In [19]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [20]:
arr.shape #menunjukkan panjang array yang vector

(8,)

In [21]:
arr1.shape #menunjukkan panjang array yang matrix

(3, 4)

In [22]:
arr.ndim #menunjukkan dimensi dari array

1

In [23]:
arr1.ndim #menunjukkan dimensi dari array matrix

2

In [24]:
arr.size #menunjukkan ukuran dari array vector

8

In [25]:
arr1.size #menunjukkan ukuran dari array matrix

12

#### Reshaping Array

In [27]:
print(arr)
print(arr.shape)

[10  4  3 19  2  1  6 18]
(8,)


In [33]:
arr.reshape(2,4) #mengubah shape/panjang array

array([[10,  4,  3, 19],
       [ 2,  1,  6, 18]])

In [34]:
arr_reshape = arr.reshape(2,4)

In [35]:
arr_reshape.ndim

2

In [36]:
arr[np.newaxis] #menjadikan array jadi satu dimensi/baris

array([[10,  4,  3, 19,  2,  1,  6, 18]])

In [37]:
arr[np.newaxis].shape 

(1, 8)

In [38]:
arr[: , np.newaxis]

array([[10],
       [ 4],
       [ 3],
       [19],
       [ 2],
       [ 1],
       [ 6],
       [18]])

In [39]:
arr[: , np.newaxis].shape

(8, 1)

In [40]:
arr.reshape(8,1)

array([[10],
       [ 4],
       [ 3],
       [19],
       [ 2],
       [ 1],
       [ 6],
       [18]])

#### Indexing and Slicing

In [41]:
mylist = [1,2,3,4,5,6,7,8]

In [42]:
mylist[1:4]

[2, 3, 4]

In [43]:
mylist[-2]

7

In [45]:
data = np.array([1,2,3,4,5,6,7,8])

In [46]:
data[0]

1

In [47]:
data[1:4]

array([2, 3, 4])

In [48]:
data[data>=4]

array([4, 5, 6, 7, 8])

In [49]:
datastr = np.array(["yunita","ainal","yulianda","fajri","malahayati"])

In [50]:
datastr[2:3]

array(['yulianda'], dtype='<U10')

In [51]:
datastr[1:4]

array(['ainal', 'yulianda', 'fajri'], dtype='<U10')

In [52]:
data[(data > 3) & (data%2==0)]

array([4, 6, 8])

In [53]:
arr

array([10,  4,  3, 19,  2,  1,  6, 18])

In [54]:
arr1 = arr[:4]
arr2 = arr[4:]

In [55]:
arr1

array([10,  4,  3, 19])

In [56]:
arr2

array([ 2,  1,  6, 18])

In [57]:
np.vstack((arr1,arr2)) 

array([[10,  4,  3, 19],
       [ 2,  1,  6, 18]])

In [58]:
a1 = np.array([
    [1,1],
    [2,2]
])
a2 = np.array([
    [3,3],
    [4,4]
])

In [59]:
np.vstack((a1,a2)) #stack secara vertikal

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [60]:
np.hstack((a1,a2)) #stack secara horizontal

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [61]:
arrsplit = np.array([
    [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15],
    [15,14,13,12,11,10,9,8,7,6,5,4,3,2,1]
])

In [62]:
np.hsplit(arrsplit,3)

[array([[ 1,  2,  3,  4,  5],
        [15, 14, 13, 12, 11]]),
 array([[ 6,  7,  8,  9, 10],
        [10,  9,  8,  7,  6]]),
 array([[11, 12, 13, 14, 15],
        [ 5,  4,  3,  2,  1]])]

In [63]:
np.hsplit(arrsplit,5)

[array([[ 1,  2,  3],
        [15, 14, 13]]),
 array([[ 4,  5,  6],
        [12, 11, 10]]),
 array([[7, 8, 9],
        [9, 8, 7]]),
 array([[10, 11, 12],
        [ 6,  5,  4]]),
 array([[13, 14, 15],
        [ 3,  2,  1]])]

#### Copy Array

In [64]:
arr

array([10,  4,  3, 19,  2,  1,  6, 18])

In [65]:
arr2 = arr.copy() #mengcopy array agar pada saat diubah tidak mengubah array awal

In [66]:
arr2 * 2

array([20,  8,  6, 38,  4,  2, 12, 36])

In [67]:
arr

array([10,  4,  3, 19,  2,  1,  6, 18])

#### Basic Operations

In [69]:
v1 = np.array([2,3,5])
v2 = np.array([1,2,3])

In [70]:
v1 + v2

array([3, 5, 8])

In [71]:
v1 * v2

array([ 2,  6, 15])

In [72]:
v1 % v2

array([0, 1, 2], dtype=int32)

In [73]:
v1/v2

array([2.        , 1.5       , 1.66666667])

In [74]:
data

array([1, 2, 3, 4, 5, 6, 7, 8])

In [75]:
data.sum()

36

In [76]:
a1

array([[1, 1],
       [2, 2]])

In [78]:
a1.sum(axis=0)

array([3, 3])

In [79]:
a1.sum(axis=1)

array([2, 4])

In [80]:
v1

array([2, 3, 5])

In [81]:
v1 * .5 #broadcasting

array([1. , 1.5, 2.5])

In [82]:
M = np.arange(0,16).reshape(4,4)

In [83]:
M

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [84]:
M.max()

15

In [85]:
M.max(axis=0)

array([12, 13, 14, 15])

In [86]:
M.max(axis=1)

array([ 3,  7, 11, 15])

In [87]:
M.min(axis=0) #axis 0 kolom

array([0, 1, 2, 3])

In [89]:
M.std(axis=1) #axis 1 baris

array([1.11803399, 1.11803399, 1.11803399, 1.11803399])

In [90]:
M.mean()

7.5

#### Matrix

In [91]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [92]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [94]:
np.random.random((2,2))

array([[0.29387309, 0.94832769],
       [0.65623951, 0.80344901]])

In [95]:
matr = np.array([
    [1,2],
    [3,4]
])

In [96]:
ones = np.ones((2,2))

In [97]:
matr + ones

array([[2., 3.],
       [4., 5.]])

In [98]:
matr + 5

array([[6, 7],
       [8, 9]])

In [99]:
matr * matr

array([[ 1,  4],
       [ 9, 16]])

In [100]:
np.matmul(matr, matr)

array([[ 7, 10],
       [15, 22]])

#### Transpose = ubah kolom jadi baris atau sebaliknya

In [102]:
Mat = np.array([
    [1,2],
    [3,4],
    [5,6]
])

In [103]:
Mat

array([[1, 2],
       [3, 4],
       [5, 6]])

In [106]:
Mat.T

array([[1, 3, 5],
       [2, 4, 6]])

In [107]:
mat_transpose = Mat.T

In [108]:
mat_transpose.reshape(6,1)

array([[1],
       [3],
       [5],
       [2],
       [4],
       [6]])

In [112]:
np.ones((3,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [113]:
random_3d = np.random.random((3,3,3))

In [114]:
random_3d.shape

(3, 3, 3)

In [115]:
random_3d.mean()

0.4348472718400932

In [116]:
random_3d.reshape((27,))

array([0.87415945, 0.84695064, 0.15542074, 0.89611425, 0.47975346,
       0.15112124, 0.25960303, 0.1378183 , 0.08323121, 0.09064935,
       0.44311406, 0.22160774, 0.54657119, 0.21262578, 0.96329895,
       0.85844008, 0.88858186, 0.05729645, 0.85604291, 0.28038212,
       0.69035709, 0.47133541, 0.59929595, 0.29595453, 0.00570064,
       0.31733808, 0.05811185])

In [117]:
random_3d.flatten()

array([0.87415945, 0.84695064, 0.15542074, 0.89611425, 0.47975346,
       0.15112124, 0.25960303, 0.1378183 , 0.08323121, 0.09064935,
       0.44311406, 0.22160774, 0.54657119, 0.21262578, 0.96329895,
       0.85844008, 0.88858186, 0.05729645, 0.85604291, 0.28038212,
       0.69035709, 0.47133541, 0.59929595, 0.29595453, 0.00570064,
       0.31733808, 0.05811185])

In [118]:
data_actual = np.random.random(100)

In [119]:
data_prediksi = np.random.random(100)

In [122]:
(1/len(data_actual)) * np.sum(np.square(data_actual - data_prediksi))

0.15895994765747032